- name: Deploy the FastAPI app
  hosts: "{{ env }}"
  tasks:
    - name: Build Docker image
      ansible.builtin.command:
        cmd: docker build -t fastapi-app:base -f Dockerfile .
        chdir: ../app

    - name: Start the FastAPI container
      ansible.builtin.command: docker run -d --name fastapi-app -p 8000:8000 fastapi-app:base
