- name: Deploy the FastAPI app
  hosts: localhost
  tasks:
    - name: Pull Docker image
      ansible.builtin.command:
        cmd: docker build -t fastapi-app:latest -f Dockerfile .
        chdir: /home/orsan/PycharmProjects/cli-agent/app

    - name: Start the FastAPI container
      ansible.builtin.command: docker run -d --name fastapi-app -p 8000:8000 fastapi-app
