- name: Deploy the FastAPI app
  hosts: "{{ env }}"
  tasks:
    - name: Upload application files
      ansible.builtin.copy:
        src: ../app/
        dest: /tmp/app/
        mode: '0755'

    - name: Build Docker image
      ansible.builtin.command:
        cmd: docker build -t fastapi-app:base -f /tmp/app/Dockerfile /tmp/app

    - name: Start the FastAPI container
      ansible.builtin.command: docker run -d --name fastapi-app -p 9000:9000 fastapi-app:base
