- name: Rollback the FastAPI app
  hosts: "{{ env }}"
  tasks:
    - name: Stop and remove the current container if running
      ansible.builtin.command: docker rm -f fastapi-app
      ignore_errors: yes

    - name: Start the FastAPI container with the "base" image
      ansible.builtin.command: docker run -d --name fastapi-app -p 9000:9000 fastapi-app:base
